--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 12.4 (Ubuntu 12.4-1.pgdg18.04+1)

-- Started on 2020-09-17 15:17:49 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 2869934)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 2845326)
-- Name: AreaAttributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AreaAttributes" (
    "AreaAttributeId" integer NOT NULL,
    "AreaId" integer NOT NULL,
    "Key" text,
    "Value" text
);


--
-- TOC entry 204 (class 1259 OID 2845332)
-- Name: AreaAttributes_AreaAttributeId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AreaAttributes" ALTER COLUMN "AreaAttributeId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AreaAttributes_AreaAttributeId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 2845334)
-- Name: AreaStatistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AreaStatistics" (
    "AreaStatisticId" integer NOT NULL,
    "AreaId" integer NOT NULL,
    "Key" text,
    "Value" numeric NOT NULL
);


--
-- TOC entry 206 (class 1259 OID 2845340)
-- Name: AreaStatistics_AreaStatisticId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AreaStatistics" ALTER COLUMN "AreaStatisticId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AreaStatistics_AreaStatisticId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 2845342)
-- Name: Areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Areas" (
    "AreaId" integer NOT NULL,
    "ParentAreaId" integer,
    "Geometry" public.geometry
);


--
-- TOC entry 208 (class 1259 OID 2845348)
-- Name: Areas_AreaId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Areas" ALTER COLUMN "AreaId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Areas_AreaId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 2888109)
-- Name: UpdateCounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UpdateCounts" (
    "UpdateCountId" integer NOT NULL,
    "LastProcessedEntry" integer
);


--
-- TOC entry 226 (class 1259 OID 2888112)
-- Name: UpdateCounts_UpdateCountId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."UpdateCounts" ALTER COLUMN "UpdateCountId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UpdateCounts_UpdateCountId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 2845350)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 5257 (class 2606 OID 2845354)
-- Name: AreaAttributes PK_AreaAttributes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AreaAttributes"
    ADD CONSTRAINT "PK_AreaAttributes" PRIMARY KEY ("AreaAttributeId");


--
-- TOC entry 5259 (class 2606 OID 2845356)
-- Name: AreaStatistics PK_AreaStatistics; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AreaStatistics"
    ADD CONSTRAINT "PK_AreaStatistics" PRIMARY KEY ("AreaStatisticId");


--
-- TOC entry 5262 (class 2606 OID 2845358)
-- Name: Areas PK_Areas; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Areas"
    ADD CONSTRAINT "PK_Areas" PRIMARY KEY ("AreaId");


--
-- TOC entry 5264 (class 2606 OID 2845360)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 5255 (class 1259 OID 2845361)
-- Name: IX_AreaAttributes_AreaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AreaAttributes_AreaId" ON public."AreaAttributes" USING btree ("AreaId");


--
-- TOC entry 5260 (class 1259 OID 2888114)
-- Name: IX_Areas_ParentAreaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Areas_ParentAreaId" ON public."Areas" USING btree ("ParentAreaId");


--
-- TOC entry 5267 (class 2606 OID 2845362)
-- Name: AreaAttributes FK_AreaAttributes_Areas_AreaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AreaAttributes"
    ADD CONSTRAINT "FK_AreaAttributes_Areas_AreaId" FOREIGN KEY ("AreaId") REFERENCES public."Areas"("AreaId") ON DELETE CASCADE;


-- Completed on 2020-09-17 15:19:39 CEST

--
-- PostgreSQL database dump complete
--

